### ISSUE TITLE
How to test this?

### ISSUE THREAD

**Issue by luzpaz** [looooo/freecad.appimage_updater#1]
Any instructions?

**Comment by looooo** [comment]
https://forum.freecadweb.org/viewtopic.php?f=8&t=44324&start=20#p403219

**Comment by looooo** [comment]
I added some instructions to the README.md:

https://github.com/looooo/freecad.appimage_updater/commit/0602fbca727799ad10ce227b03f08c3e4bd0c311

**Comment by luzpaz** [comment]
awesome, thanks!
