### ISSUE TITLE
Regarding false update trigger.

### ISSUE THREAD

**Issue by antony-jr** [looooo/freecad.appimage_updater#6]
Whenever a cron job is executed, a new binary is uploaded. Since some data which is not relevant to FreeCAD is changed on each build the AppImages also defer **even if the FreeCAD version is not updated**. This results in **SHA1 hash change** which triggers update in any **AppImage Update tool**.

**My understanding is that the filename used by FreeCAD AppImage can tell the new version and old version, if so I think we can use this factor to tell if we need to update or not even if the SHA1 hash differs.** Since we have our own updater inside FreeCAD we can modify the delta update however we want.

Can we implement this?

Since we have bindings to freecad itself, is there a way to get this **revision number or version** from python? if not we would have to depend on the filename but that is not very reliable. 

**The only thing to watch out is to never change the naming scheme of FreeCAD in the future (i.e the same one we are still using now FreeCAD_\<version\>-\<build no]>-Linux-Conda_glibc2.12-\<arch\>.AppImage)**

But just in case we will of course have fail-safe to use the regular delta update.

**Comment by looooo** [comment]
good idea.

getting the version is easy:
```
>> import FreeCAD
>> FreeCAD.Version()
['0', '20', '24562 (Git)', '/home/conda/feedstock_root/build_artifacts/git_cache/github.com/FreeCAD/FreeCAD master', '2021/03/27 14:37:48', 'master', '8277b3f9e9b66092a58625f3a2a87a0d60dcc580']
```

So we can use something like this to get revision
```
>> import FreeCAD
>> FreeCAD.Version()[2].split(" ")[0]
'24562'
```

**Comment by antony-jr** [comment]
> good idea.
> 
> getting the version is easy:
> 
> ```
> >> import FreeCAD
> >> FreeCAD.Version()
> ['0', '20', '24562 (Git)', '/home/conda/feedstock_root/build_artifacts/git_cache/github.com/FreeCAD/FreeCAD master', '2021/03/27 14:37:48', 'master', '8277b3f9e9b66092a58625f3a2a87a0d60dcc580']
> ```
> 
> So we can use something like this to get revision
> 
> ```
> >> import FreeCAD
> >> FreeCAD.Version()[2].split(" ")[0]
> '24562'
> ```

Great. Thanks for the hint. PR will follow shortly.
